In [2]:
import numpy as np


a = np.array([[3,7,8], [2,1,9]])
print(f'matrix: \n{a}\ndimension: {a.ndim}\nshape: {a.shape}')


matrix: 
[[3 7 8]
 [2 1 9]]
dimension: 2
shape: (2, 3)


In [3]:
# Get specific element
a[1,2]

9

In [4]:
# Get specific column
# e.g. second column
a[:,1]

array([7, 1])

In [5]:
# Get specific row
# e.g. first row
a[0,:]

array([3, 7, 8])

In [6]:
# numpy.arange creates arrays with regularly incrementing values.
b0 = np.arange(5,8,0.2) # [5, 5.2, ..., 7.8]
print(b0)

[5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8]


In [7]:
# numpy.linspace will create arrays with a specified number of elements,
# and spaced equally between the specified beginning and end values
b1 = np.linspace(5, 20, 4)
b1

array([ 5., 10., 15., 20.])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# scalar * np.ones()
5 * np.ones((4, 4), dtype=int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
# np.zeros()
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# np.full(shape, value)
np.full((1,2), 6)

array([[6, 6]])

In [12]:
# a.transpose() == a.T => calculate the transpose
a.T

array([[3, 2],
       [7, 1],
       [8, 9]])

In [13]:
b3 = np.mgrid[0:2,0:3]
# help(np.mgrid)
print(b3)
b3.shape

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


(2, 2, 3)

In [14]:
# np.reshape + np.arange
b5 = np.arange(1,13,1)
b5
b5.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# np.full_like  => use b6's shape
b6 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.full_like(b6, 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [16]:
# identity
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
# random
np.random.randint(1, 10, (3,4)) #(from, till, (shape))

array([[8, 3, 8, 9],
       [1, 1, 5, 8],
       [6, 1, 5, 9]])

In [18]:
# initialize a specific array
output = np.ones((5,5))
inner = np.zeros((3,3))
inner[1,1] = 9
output[1:4, 1:4] = inner
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#### Linear Algebra 
b7 = np.array([[1,2,3],[7,8,6],[4,5,9]])
b7 + 2
b7 - 2
b7 / 2
b7 * 2
b7 ** 2
b8 = 3 * np.ones((3, 4))
b7 @ b8 # np.matmul(b7, b8)
np.linalg.det(b7) #det

-27.0

In [20]:
#np.tile(69, (2, 3))
print(np.arange(0,5))
# print(list(np.array([0,1,2,3,4]))) cast np.array to list and vice versa

[0 1 2 3 4]


In [21]:
# create a 6*5 matrix which value are a sequence from 1 to 30
b9 = np.arange(1, 31).reshape(6,5)
print(b9)
print(b9[2:4,0:2])
print(b9[np.arange(0,4),np.arange(1,5)])
print(b9[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]


# vstack and hstack

In [28]:
a = np.arange(1, 31).reshape(5, 6)
a0 = np.arange(31, 37)
a = np.vstack((a, a0))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

# flatten

In [ ]:
a = np.array()